site_name: Waterfox musl Builds
site_url: https://vr-ski.github.io/waterfox-musl-builds
repo_url: https://github.com/vr-ski/waterfox-musl-builds
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - md_in_html
